blocknative/go-ethereum

- accounts/abi/bind/backends/dropped_tx_subscription.go
- core/events.go
- core/tx_pool.go
- eth/filters/dropped_tx_subscription.go
- eth/filters/filter.go
- eth/filters/peers_api.go
At Chris's request, adding full transactions instead of hashes in the custom mempool feeds.
Additionally, I've added timestamps in nano-seconds for when each message is emitted.
Note that because the hashes have been replaced with full transactions, this breaks backwards compatibility with the last release.
> accounts,core, eth/filters: Return full transactions instead of hashes

- eth/fetcher/tx_fetcher.go
- eth/filters/api.go
- eth/filters/dropped_tx_subscription.go
- eth/filters/peers_api.go
The timestamps recorded when transactions are received weren't
being cleared when transactions were dropped or rejected. This could
mean that a transaction was dropped or rejected due to insufficient
price (or perhaps other reasons), but the timestamp would be retained
until it was seen again, and the earlier timestamp would be used
with a later receipt of the transaction.
This ensures that rejected transactions are removed from the timestamp
map as soon as they are rejected, and stops relying on the drop feed
(which may have no subscribers) for removing timestamps on dropped
transactions.
> Better cleanup of transaction p2p timestamps

- eth/filters/dropped_tx_subscription.go
Adds nil tx check back to `newRPCPendingTransaction` handler which was accidentally removed in the last PR https://github.com/blocknative/go-ethereum/pull/12/files#diff-4c749681b46f7485aaf69749644b6abe20ccab355a64519ccb7f665ecbd08f10L35
> add nil tx check

- core/revert_cache.go
- core/state_processor.go
- eth/filters/peers_api.go
Hypothetically, if a transaction reverted in one version of a block
and succeeded in reorged versions of the block, the successful transaction
could show up with the revert reason. Caching on both the block hash
and transaction hash prevents this.
> Cache revert reasons by transaction and block hash

- core/revert_cache.go
- eth/filters/peers_api.go
This adds "receipt.status" to the receipt data so that we can always
identify failed transactions even if they lack a revert reason.
It will also provide a hex encoded revert reason if the revert reason
cannot be ABI decoded.
> Better revert handling

- eth/tracers/call_tracer.go
The tracer generally assumes well formed opcodes. When there are not
enough items on the stack for a given opcode, it panics, causing Geth
to crash.
This catches those panics and notes it on the call stack to avoid
crashes while informing the user of the issue.
> Catch panics in traces

- core/blockchain.go
- core/revert_cache.go
- eth/filters/peers_api.go
This makes two fixes to protect against node lockups due to
feeds.
The first is to use buffered channels. Without a buffered channel,
the block producer must wait until the consumer has taken a block
before it can continue producing blocks. Generally this isn't an
issue, but it could cause an underperforming consumer to bring
everything else grinding to a hault.
The bigger underlying issue is that the NewFullBlocksWithPeers
implementation was only cleaning up 1 of 2 subscriptions, which
meant the other channel was sticking around despite no consumers.
Once the producer tries to send another message to it, it will block
indefinitely. Buffered channels would have merely delayed this
until the buffer filled up, but the eventual result would have been
the same (but buffered channels are still …
> Use buffered channels, do better cleanup

- accounts/accounts.go
- core/asm/lexer.go
- core/rawdb/accessors_chain.go
- ethclient/ethclient.go
- graphql/graphql.go
- interfaces.go
- les/server_handler.go
- params/version.go
- trie/sync.go
Reverts blocknative/go-ethereum#36
> Revert "Merge/v1.10.15"

- core/state_processor.go
- core/tx_pool.go
- core/types/transaction.go
- eth/backend.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- les/client.go
- This PR adds support from eth_callBundle RPC which was originally forked from flashbots MEV-GETH.
- Addition on top of mev-geth call bundle RPC are support for unsigned txns, payload modifications, and the addition of the geth internal struct logger to output JSON stack traces of EVM calls
> Feature : Unsigned Txn Bundle Simulation

- eth/tracers/native/goCallTracer.go
- eth/tracers/native/txnOpCodeTracer.go
- Returns old tracer to expected return values.
- This logic means we always return the top level trace and no subtraces, which we expect in our current system. 
- Handling will be added in Blocknative side code bases to handle the differences in returning subtraces vs not.
> Fix | Old tracer error returning

- .github/workflows/release.yml
For the private testnet we need to run a bootnode so we need to build the bootnode cmd binary.
Release with this work included: https://github.com/blocknative/go-ethereum/releases/tag/v1.10.23-build-bootnode
> add bootnode binary build to release action

- core/state_processor.go
Replaces PR #81 
This routine handles the details of the gas accounting for state-related operations, like rebates and operations that depend on existing state values when calculating gas cost. Without calling it, we incorrectly calculate transactions in bundles that come after a transaction that touches one of these facilities.
This can be tested with this script that bundles txs from the mempool and sends them to callBundle on both the prod auction gateway and a local tunnel to a sim node. Without the fix, it fails 99% of the time. With this fix, it succeeds 100% of the time. https://github.com/tyler-smith/bundles-go/blob/TS_testCallBundle/examples/testCallBundle/main.go
This change brings the code to be inline with mev-geth and other mev-geth forks.
> BUGFIX: Enable state finalization.

- core/state_processor.go
- eth/tracers/blocknative/blocknative.go
- eth/tracers/blocknative/txnOpCodeTracer.go
- eth/tracers/register_blocknative.go
- Move `txnOpCodeTracer` from `eth/tracers/native` to `eth/tracers/blocknative`.
- Register the `eth/tracers/blocknative` tracers (i.e. `txnOpCodeTracer`) from `eth/tracers` instead of from inside `eth/tracers/blocknative` directly as other tracers do.
- This allows us to avoid importing `eth/tracers` which imports `core`, and allows us to import the `eth/tracers/blocknative` inside `core` itself.
- Remove duplicated `txnOpCodeTracer` from `core/state_processor.go` and use `eth/tracers/blocknative.txnOpCodeTracer` instead.
Note that in the future we can easily life `eth/tracers/blocknative` into it's own repo, `github.com/blocknative/tracers`, which we can reuse for Polygon and any other geth-based chains.
> Consolidate tracer code

- eth/filters/trace_api.go
- eth/tracers/blocknative/cache/trace_cache.go
- eth/tracers/blocknative/utils.go
- Add trace cache to trace_api.go:traceTx.
- Modify addrToHex to not require a Keccak hash, making it much faster.
> Trace cache and perf improvements

- eth/tracers/blocknative/blocknative.go
- eth/tracers/blocknative/txnOpCodeTracer.go
- eth/tracers/internal/tracetest/txnOpCodeTracer_test.go
Currently, the trace duration is reported in a human-oriented string format. To facilitate easy tracking of performance, we want to change this to an integer with a consistent time resolution.
> tweak: Use int nanoseconds instead of string for duration.

- eth/tracers/blocknative/tracer.go
- eth/tracers/internal/tracetest/blocknative_test.go
This lets us specify specific tests to run using a `-file` flag, logging level with a `-loglevel` flag, and makes sure tests don't interfere with each other via the global cache.
> Add test flags and clear cache between tests to fix deterministic failures.

- eth/tracers/native/accountTouchTracer.go
The tracer will help us with the OFAC filtering on Boost.
> Add touched accounts tracer

- eth/tracers/blocknative/decoder/asset.go
If for any reason the tokenID for an ERC721 or ERC1155 transfer is nil, skip calculating the URI. There is a most likely a better/more robust solution but this should prevent us from dying until such a solution is in place.
Example scenario: A Contract implements ERC1155, and additionally the same transfer method as ERC20. However the Contract is _not_ an ERC20 it just has one of the same methods. When we parse transfers, we will still collect this as a transfer but there is no tokenID because it's not an ERC1155 transfer. Later when getting metadata, we see that the contract is not an ERC20 but is an ERC1155 so we get the metadata for that. It is now not safe to assume the transfer has a non-nil tokenID.
> fix: Don't panic if tokenID is nil

- eth/filters/trace_api.go
This will ensure that panics in the tracer/decoder don't cause the entire node to restart. But no notification of the failure is indicated to the client, so it will simply stop seeing messages until it times out and reconnects on its own. A future improvement would be one of either sending the client a message telling it to reconnect or attempting to reconstruct a new go-routine transparently.
> tweak: Recover from any panics in trace streams.

- accounts/abi/bind/backends/simulated.go
- core/events.go
- core/txpool/blobpool/blobpool.go
- core/txpool/legacypool/legacypool.go
- core/txpool/subpool.go
- core/txpool/txpool.go
- eth/api_backend.go
- eth/filters/dropped_tx_subscription.go
- eth/filters/filter_system.go
- eth/filters/trace_api.go
- internal/ethapi/backend.go
- les/api_backend.go
In 60 seconds we're seeing 191 pending txs, which is what the current emitter would be seeing, and 632 future txs.
> tweak: Add future tx events to trace API.

- eth/tracers/blocknative/decoder/balances.go
- eth/tracers/blocknative/decoder/decoder.go
- eth/tracers/blocknative/tracer.go
- eth/tracers/internal/tracetest/testdata/blocknative/with_decoding/inner_create.json
- eth/tracers/internal/tracetest/testdata/blocknative/with_decoding/multi_contracts_transfers.json
Change the order of operations when decoding call frames to address various balance change issues including:
- Missing native transfers to accounts that we fail to decode contracts for correctly.
- Unnecessary "0 transfers" that result from some calls.
- False gas transfer information on traces for reverting transactions.
> Fixes for balance changes
